CREATE TABLE IF NOT EXISTS lesson_qa_likes (
    like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qa_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_lesson_qa_like_user UNIQUE (qa_id, user_id),
    CONSTRAINT lesson_qa_likes_qa_fk FOREIGN KEY (qa_id)
        REFERENCES lesson_qa (qa_id) ON DELETE CASCADE,
    CONSTRAINT lesson_qa_likes_user_fk FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_lesson_qa_likes_qa ON lesson_qa_likes (qa_id);
CREATE INDEX IF NOT EXISTS idx_lesson_qa_likes_user ON lesson_qa_likes (user_id);
