package com.example.back_end.entity.enums;

public enum NotificationType {
    GENERIC, COURSE_SUBMITTED, COURSE_APPROVED, COURSE_REJECTED,INSTRUCTOR_FOLLOWED,
    TEACHER_APPLICATION_SUBMITTED, TEACHER_APPLICATION_APPROVED, TEACHER_APPLICATION_REJECTED,
    NEW_ENROLLMENT, NEW_REVIEW, NEW_QUESTION, CERTIFICATE_ISSUED,
    COURSE_ANNOUNCEMENT, PAYOUT_REQUESTED, PAYOUT_PAID, PAYOUT_REJECTED,
    COURSE_REPORTED,
    ADMIN_ACTIVITY
}
