spring.application.name=back_end
debug=false
logging.level.org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger=OFF

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.detect-encoding=true
spring.flyway.clean-disabled=true

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=86400000 
jwt.refresh-token-remember-expiration=2592000000

aws.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}

cloudfront.domain=${CLOUDFRONT_DOMAIN}
cloudfront.key-pair-id=${CLOUDFRONT_KEY_PAIR_ID}
cloudfront.private-key-path=${CLOUDFRONT_PRIVATE_KEY_PATH}

mediaconvert.role-arn=${MEDIACONVERT_ROLE_ARN}
mediaconvert.endpoint=${MEDIACONVERT_ENDPOINT}

app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:5173}
server.cookie.secure=${COOKIE_SECURE:false}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174}

ai.service.base-url=${AI_SERVICE_URL:http://localhost:8000}
# gg
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account

# # Facebook OAuth2 Configuration
spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=public_profile,email

payos.client-id=${PAYOS_CLIENT_ID:}
payos.api-key=${PAYOS_API_KEY:}
payos.checksum-key=${PAYOS_CHECKSUM_KEY:}
payos.return-url=${PAYOS_RETURN_URL:http://localhost:5173/payment/success}
payos.cancel-url=${PAYOS_CANCEL_URL:http://localhost:5173/payment/cancel}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.elasticsearch.uris=${ES_URIS:http://localhost:9200}

