package com.example.back_end.notification.domain.enums;

public enum NotificationType {
    GENERIC, COURSE_SUBMITTED, COURSE_APPROVED, COURSE_REJECTED,INSTRUCTOR_FOLLOWED, INSTRUCTOR_NEW_COURSE,
    TEACHER_APPLICATION_SUBMITTED, TEACHER_APPLICATION_APPROVED, TEACHER_APPLICATION_REJECTED,
    NEW_ENROLLMENT, NEW_REVIEW, NEW_QUESTION, CERTIFICATE_ISSUED,
    COURSE_ANNOUNCEMENT, PAYOUT_REQUESTED, PAYOUT_PAID, PAYOUT_REJECTED,
    COURSE_REPORTED, LEARNING_REMINDER, NEW_VOUCHER,

    ADMIN_ACTIVITY, SUPPORT_MESSAGE
}
